### ISSUE TITLE
Rewrite/rethink docker.mysql-local entrypoint.sh

### ISSUE THREAD

**Issue by rfay** [drud/docker.mysql-local#25]
## What happened (or feature request):

The entrypoint.sh for this container is impressively complex, and obviously has a significant lineage. It's extremely difficult to maintain, and the generalizations in it are (generally speaking) not useful.

I recommend we take just a bit of time to rewrite the entrypoint from scratch for our needs in mysql-local.

Suggestions:
* Assume mysqld as the command instead of using $@
* Assume /var/lib/mysql as datadir instead of trying to figure it out.
* Do only things that are actually required by our current usage (mysql-local)
* Check for errors and announce them.

## Related source links or issues:

**Comment by rfay** [comment]
This was completed in #26

**Comment by rfay** [comment]
Reopening. I was wrong to close this, as there's much remaining to be done.

**Comment by cweagans** [comment]
There was some progress on this in https://github.com/drud/mariadb-local/pull/30
