### ISSUE TITLE
Clean up test container

### ISSUE THREAD

**Issue by cweagans** [drud/docker.mysql-local#29]
## What happened (or feature request):

test/testerver.sh creates a container with the name `testserver`. At the end of the script, we should clean up that container so that the test script can be run repeatedly without having to manually delete the container.

This probably doesn't make too much difference on the Circle CI environment, but will help for local development.

## Related source links or issues:

**Comment by rfay** [comment]
Works for me! IMO you can fix this in your rework to mariadb.
