### ISSUE TITLE
Update README.md to reflect switch to mariadb

### ISSUE THREAD

**Issue by cweagans** [drud/docker.mysql-local#32]
## What happened (or feature request):

We switched to mariadb. We should update the readme, as it currently contains a bunch of mysql stuff.

## Related source links or issues:

**Comment by rfay** [comment]
The entire README.md should be replaced with something shorter and that caters to ddev. It would be OK to do this in the switchover PR if you want, but you've already got approval for that so maybe better to wait.

**Comment by rickmanelius** [comment]
Related https://github.com/drud/ddev/issues/251

**Comment by rfay** [comment]
We'll reopen if we get there.
